### ISSUE TITLE
Yo!

### ISSUE THREAD

**Issue by Kadantte** [cthuluhoop123/nhentai-js#9]
Is there a way to push the result into Browser like we use this script as an API?

Check here: https://nhent.ai/api/galleries/all

**Comment by cthuluhoop123** [comment]
I'm not sure what you're looking for, but you can certainly throw this onto a backend and rely on Ajax ?

**Comment by Kadantte** [comment]
Here what i mean please see the picture below
I want to show the result as json file like that

![52363122_2592620140811503_458976002140274688_n](https://user-images.githubusercontent.com/11579313/53357338-96516280-3925-11e9-899f-04be2e60d258.png)

**Comment by cthuluhoop123** [comment]
Yes that completely possible. Just create an express backend that you can make ajax calls to :)
